CREATE USER  C##is210 IDENTIFIED BY is210;
GRANT CONNECT, RESOURCE TO C##is210;
GRANT CREATE SESSION TO C##is210;
GRANT UNLIMITED TABLESPACE TO C##is210;
GRANT CREATE TABLE TO C##is210;
GRANT CREATE VIEW TO C##is210;
GRANT CREATE ANY TRIGGER TO C##IS210;
GRANT CREATE PROCEDURE TO C##IS210;
GRANT CREATE SEQUENCE TO C##IS210;
GRANT CREATE TRIGGER TO C##IS210;

